version: "3"

services:
  app:
    build: ./
    environment:
      MONGO_HOST: mongodb
    ports:
      - "80:8000"
    restart: always
    depends_on:
      - mongodb
    links:
      - mongodb

  mongodb:
    image : mongo
    environment:
      MONGO_INITDB_DATABASE: monitor
    ports:
      - 27017:27017
    restart: always